CUDA_VISIBLE_DEVICES=0 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M-Instruct" --peft-path="./results/SmolLM2-135M-Instruct/peft_100/" --run-name="eval_results_SmolLM2-135M-Instruct"  --batch-size=16 --quantization=4 --category="stem"
CUDA_VISIBLE_DEVICES=0 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M-Instruct" --peft-path="./results/SmolLM2-135M-Instruct/peft_100/" --run-name="eval_results_SmolLM2-135M-Instruct"  --batch-size=16 --quantization=4 --category="social_sciences"
CUDA_VISIBLE_DEVICES=0 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M-Instruct" --peft-path="./results/SmolLM2-135M-Instruct/peft_100/" --run-name="eval_results_SmolLM2-135M-Instruct"  --batch-size=16 --quantization=4 --category="humanities"

CUDA_VISIBLE_DEVICES=0 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M-Instruct" --peft-path="./results/SmolLM2-360M-Instruct/peft_100/" --run-name="eval_results_SmolLM2-360M-Instruct"  --batch-size=16 --quantization=4 --category="stem"
CUDA_VISIBLE_DEVICES=0 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M-Instruct" --peft-path="./results/SmolLM2-360M-Instruct/peft_100/" --run-name="eval_results_SmolLM2-360M-Instruct"  --batch-size=16 --quantization=4 --category="social_sciences"
CUDA_VISIBLE_DEVICES=0 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M-Instruct" --peft-path="./results/SmolLM2-360M-Instruct/peft_100/" --run-name="eval_results_SmolLM2-360M-Instruct"  --batch-size=16 --quantization=4 --category="humanities"

CUDA_VISIBLE_DEVICES=1 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M" --peft-path="./results/SmolLM2-135M-Instruct/peft_100/" --run-name="eval_results_SmolLM2-135M"  --batch-size=16 --quantization=4 --category="stem"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M" --peft-path="./results/SmolLM2-135M-Instruct/peft_100/" --run-name="eval_results_SmolLM2-135M"  --batch-size=16 --quantization=4 --category="social_sciences"
CUDA_VISIBLE_DEVICES=1 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-135M" --peft-path="./results/SmolLM2-135M-Instruct/peft_100/" --run-name="eval_results_SmolLM2-135M"  --batch-size=16 --quantization=4 --category="humanities"

CUDA_VISIBLE_DEVICES=0 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M" --peft-path="./results/SmolLM2-360M_300Rounds/peft_300/" --run-name="eval_results_SmolLM2-360M"  --batch-size=16 --quantization=4 --category="stem"
CUDA_VISIBLE_DEVICES=0 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M" --peft-path="./results/SmolLM2-360M_300Rounds/peft_300/" --run-name="eval_results_SmolLM2-360M"  --batch-size=16 --quantization=4 --category="social_sciences"
CUDA_VISIBLE_DEVICES=0 python flowertune-eval-general-nlp/eval.py --base-model-name-path "HuggingFaceTB/SmolLM2-360M" --peft-path="./results/SmolLM2-360M_300Rounds/peft_300/" --run-name="eval_results_SmolLM2-360M"  --batch-size=16 --quantization=4 --category="humanities"
